CREATE DATABASE SOCCER;
USE SOCCER;

CREATE TABLE Leagues (
    LEAGUE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LEAGUE_NAME VARCHAR(20) NOT NULL UNIQUE KEY
    )ENGINE=InnoDB;

    CREATE TABLE Field_home (
	FIELD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIELD_NAME VARCHAR(20) NOT NULL UNIQUE KEY,
    FIELD_ADDRESS VARCHAR(40) NOT NULL UNIQUE KEY,
    FIELD_CITY VARCHAR(10) NOT NULL,
    FIELD_STATE VARCHAR (10) NOT NULL
    )ENGINE=InnoDB;
    
CREATE TABLE Team (
	TEAM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEAM_NAME VARCHAR(20) NOT NULL UNIQUE KEY,
    LEAGUE_ID INT NOT NULL,
    FIELD_ID INT NOT NULL UNIQUE KEY,
    FOREIGN KEY (LEAGUE_ID)
						REFERENCES Leagues(LEAGUE_ID),
	FOREIGN KEY (FIELD_ID)
						REFERENCES Field_home(FIELD_ID)
)ENGINE=InnoDB;

CREATE TABLE Player (
	PLAYER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLAYER_NAME VARCHAR (30) NOT NULL,
    PHONE_NUMBER VARCHAR(12) UNIQUE KEY,
    PLAYER_DOB DATE NOT NULL,
    JERSEY_NUMBER INT (3) UNIQUE KEY,
    PLAYER_POSITION VARCHAR (10) NOT NULL,
    TEAM_ID INT NOT NULL,
    FOREIGN KEY (TEAM_ID)
						REFERENCES Team(TEAM_ID)
)ENGINE= InnoDB;

CREATE TABLE Matches (
	MATCH_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEAM_ID_1 INT NOT NULL,
    TEAM_ID_2 INT NOT NULL,
    FIELD_ID INT NOT NULL,
	MATCH_DATE DATE NOT NULL,
    FOREIGN KEY (FIELD_ID)
						REFERENCES Field_home(FIELD_ID),
    FOREIGN KEY (TEAM_ID_1)
						REFERENCES Team(TEAM_ID),
	FOREIGN KEY (TEAM_ID_2)
						REFERENCES Team(TEAM_ID)
)ENGINE=InnoDB;

CREATE TABLE Score (
	SCORE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GOAL_TIME TIME NOT NULL,
    MATCH_ID INT NOT NULL,
    TEAM_ID_1 INT,
    TEAM_ID_2 INT,
    FOREIGN KEY (TEAM_ID_1)
						REFERENCES Team (TEAM_ID),
	FOREIGN KEY (TEAM_ID_2)
						REFERENCES Team (TEAM_ID)
)ENGINE = InnoDB;


/**    LEAGUES     **/
INSERT INTO Leagues (LEAGUE_NAME) VALUES ('NY Youth League');
INSERT INTO Leagues(LEAGUE_NAME) VALUES ('NJ Senior League');

/**    FIELD     **/
INSERT INTO Field_home (FIELD_NAME, FIELD_ADDRESS, FIELD_CITY, FIELD_STATE) 
VALUES ('Dyker Beach', '123xyz', 'Brooklyn', 'NY');
INSERT INTO Field_home (FIELD_NAME, FIELD_ADDRESS, FIELD_CITY, FIELD_STATE)
VALUES('Old Trafford', '222xyz', 'Harlem', 'NY');
INSERT INTO Field_home (FIELD_NAME, FIELD_ADDRESS, FIELD_CITY, FIELD_STATE)
VALUES('Santiago', '333xyz', 'Long City', 'NY');
INSERT INTO Field_home (FIELD_NAME, FIELD_ADDRESS, FIELD_CITY, FIELD_STATE)
VALUES('Long Field', '565xyz', 'Rego Park', 'NY');
INSERT INTO Field_home (FIELD_NAME, FIELD_ADDRESS, FIELD_CITY, FIELD_STATE)
VALUES('Allianz Stadium', '555xyz', 'Flushing', 'NY');
INSERT INTO Field_home (FIELD_NAME, FIELD_ADDRESS, FIELD_CITY, FIELD_STATE)
VALUES('Red Island', '666xyz', 'Jamaica', 'NY');

/**    TEAM     **/
INSERT INTO Team (TEAM_NAME, LEAGUE_ID, FIELD_ID) VALUES ('Brazil', 1, 1);
INSERT INTO Team (TEAM_NAME, LEAGUE_ID, FIELD_ID) VALUES ('United States', 2, 2);
INSERT INTO Team (TEAM_NAME, LEAGUE_ID, FIELD_ID) VALUES ('England', 1, 3);
INSERT INTO Team (TEAM_NAME, LEAGUE_ID, FIELD_ID) VALUES ('Argentina', 2, 4);
INSERT INTO Team (TEAM_NAME, LEAGUE_ID, FIELD_ID) VALUES ('Equador', 1, 5);
INSERT INTO Team (TEAM_NAME, LEAGUE_ID, FIELD_ID) VALUES ('Uruguai', 2, 6);

/**    PLAYER     **/
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player1', '1121141121' ,'1999-12-31', 1, 'Goalkeeper' , 1);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player2', '1121141131', '1998-12-31', 10, 'Defense' , 2);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player3', '1121141141', '1997-12-31', 9, 'Striker' , 3);

INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player4', '1121141151' ,'1996-12-31', 2, 'Goalkeeper' , 2);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player5', '1121141161', '1995-12-31', 11, 'Defense' , 2);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player6', '1121141171', '1994-12-31', 7, 'Striker' , 2);

INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player7', '1121142151' ,'1996-12-31', 3, 'Goalkeeper' , 3);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player8', '1121143161', '1995-12-31', 12, 'Defense' , 3);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player9', '1121144171', '1994-12-31', 8, 'Striker' , 3);

INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player10', '3121142151' ,'1996-12-31', 4, 'Goalkeeper' , 4);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player11', '2121143161', '1995-12-31', 13, 'Defense' , 4);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player12', '11211449980', '1994-12-31', 22, 'Striker' , 4);

INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player13', '1221142151' ,'1996-12-31', 5, 'Goalkeeper' , 5);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player14', '1321143161', '1995-12-31', 14, 'Defense' , 5);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player15', '1421144171', '1994-12-31', 17, 'Striker' , 5);

INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player16', '1222142451' ,'1996-12-31', 6, 'Goalkeeper' , 6);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player17', '1323149161', '1995-12-31', 15, 'Defense' , 6);
INSERT INTO Player (PLAYER_NAME, PHONE_NUMBER, PLAYER_DOB, JERSEY_NUMBER, PLAYER_POSITION, TEAM_ID) 
VALUES ('Player18', '1427144871', '1994-12-31', 20, 'Striker' , 6);

/**    MATCHES     **/
INSERT INTO Matches (TEAM_ID_1, TEAM_ID_2, FIELD_ID, MATCH_DATE) VALUES (1,2,1, '2018-12-31');
INSERT INTO Matches (TEAM_ID_1, TEAM_ID_2, FIELD_ID, MATCH_DATE) VALUES (3,4,3, '2018-10-18');
INSERT INTO Matches (TEAM_ID_1, TEAM_ID_2, FIELD_ID, MATCH_DATE) VALUES (5,6,6, '2018-07-17');

/**    SCORE     **/
INSERT INTO Score (GOAL_TIME, MATCH_ID, TEAM_ID_1) VALUES ('19:00', 1, 1);
INSERT INTO Score (GOAL_TIME, MATCH_ID, TEAM_ID_2) VALUES ('90:00', 2, 1);
INSERT INTO Score (GOAL_TIME, MATCH_ID, TEAM_ID_2) VALUES ('21:00', 3, 1);
