SELECT
	M.MATCH_ID, T.TEAM_NAME, P.PLAYER_NAME, P.JERSEY_NUMBER, 
    DATE_FORMAT(M.MATCH_DATE, "%m/%d/%Y") AS MATCH_DATE, S2.GOAL_TIME
FROM(
	SELECT
		MATCH_ID, MIN(GOAL_TIME) AS GOAL_TIME
	FROM
		SCORE
	GROUP BY
		MATCH_ID
) S1
INNER JOIN
	SCORE S2
ON
	S1.MATCH_ID = S2.MATCH_ID AND S1.GOAL_TIME = S2.GOAL_TIME
INNER JOIN
	PLAYER P
ON
	S2.PLAYER_ID = P.PLAYER_ID
INNER JOIN
	TEAM T
ON
	P.TEAM_ID = T.TEAM_ID
INNER JOIN
	MATCHES M
ON
	S2.MATCH_ID = M.MATCH_ID
ORDER BY
	M.MATCH_ID ASC;
