SELECT
	M.MATCH_ID, T.TEAM_NAME, P.PLAYER_NAME, P.JERSEY_NUMBER, M.MATCH_DATE, S.GOAL_TIME
FROM
	SCORE S
INNER JOIN
	PLAYER P
ON
	S.PLAYER_ID = P.PLAYER_ID AND P.IS_PLAYER_CAPTAIN = 1
INNER JOIN
	TEAM T
ON
	P.TEAM_ID = T.TEAM_ID
INNER JOIN
	MATCHES M
ON
	S.MATCH_ID = M.MATCH_ID
ORDER BY
	S.MATCH_ID ASC
