## RUN THIS SQL SCRIPT AFTER CREATE SOCCER DATABASE ##
INSERT INTO TEAM_PLAYER(PLAYER_ID, TEAM_ID)
	SELECT T2.PLAYER_ID, T1.TEAM_ID FROM Team AS T1 
			INNER JOIN Player AS T2 ON T1.TEAM_ID = T2.TEAM_ID