
CREATE VIEW MATCH_SCORES AS
SELECT
	M.MATCH_ID, M.TEAM_ID_1, T1.TEAM_NAME AS TEAM_NAME_1, M.TEAM_ID_2, T2.TEAM_NAME AS TEAM_NAME_2,
    SUM(CASE WHEN M.TEAM_ID_1 = P.TEAM_ID THEN 1 ELSE 0 END) AS TEAM_1_SCORE,
    SUM(CASE WHEN M.TEAM_ID_2 = P.TEAM_ID THEN 1 ELSE 0 END) AS TEAM_2_SCORE
FROM
	MATCHES M
INNER JOIN
	TEAM T1
ON
	M.TEAM_ID_1 = T1.TEAM_ID
INNER JOIN
	TEAM T2
ON
	M.TEAM_ID_2 = T2.TEAM_ID
LEFT JOIN
	SCORE S
ON
	M.MATCH_ID = S.MATCH_ID
INNER JOIN
	PLAYER P
ON
	S.PLAYER_ID = P.PLAYER_ID
GROUP BY M.MATCH_ID, M.TEAM_ID_1, M.TEAM_ID_2;
