DELIMITER $$
CREATE PROCEDURE GetPlayers()
BEGIN
    SELECT 
	P.PLAYER_ID, P.PLAYER_NAME, P.PHONE_NUMBER, P.PLAYER_DOB, P.JERSEY_NUMBER, 
	P.IS_PLAYER_CAPTAIN, PP.PLAYER_POSITION_ID, PP.POSITION_NAME, T.TEAM_ID, T.TEAM_NAME, 
	L.LEAGUE_ID, L.LEAGUE_NAME, S.SEASON_ID, S.SEASON_NAME
    FROM
	Player P
    JOIN
	Player_Position PP
    ON
	P.PLAYER_POSITION_ID = PP.PLAYER_POSITION_ID
    JOIN
	Team T
    ON
	P.TEAM_ID = T.TEAM_ID
    JOIN
	LEAGUES L
    ON
	T.LEAGUE_ID = L.LEAGUE_ID
    JOIN
	SEASON S
    ON
	L.SEASON_ID = S.SEASON_ID;
END $$
DELIMITER ; 