DELIMITER $$
CREATE PROCEDURE GetTopScoreByPosition(IN positionName VARCHAR(30))
BEGIN
SELECT T1.PLAYER_NAME, COUNT(T2.PLAYER_ID) AS GOALS, T3.POSITION_NAME 
	FROM PLAYER AS T1
	INNER JOIN SCORE AS T2 ON T1.PLAYER_ID=T2.PLAYER_ID
	INNER JOIN PLAYER_POSITION AS T3 ON T1.PLAYER_POSITION_ID=T3.PLAYER_POSITION_ID
WHERE T3.POSITION_NAME = positionName
GROUP BY T1.PLAYER_ID
ORDER BY COUNT(T2.PLAYER_ID) DESC;
END $$
DELIMITER ;

-- CALL GetTopScoreByPosition('Center Striker');