DELIMITER $$
CREATE PROCEDURE GetByTeamName(IN teamName VARCHAR(30))
BEGIN
SELECT T1.PLAYER_NAME AS Name
		,T1.PHONE_NUMBER AS Phone
		,T1.PLAYER_DOB AS DOB
		,T1.JERSEY_NUMBER AS Jersey_Number
		,T3.POSITION_NAME AS Current_position
		,T2.TEAM_NAME AS Current_Team
	FROM PLAYER AS T1
		INNER JOIN TEAM AS T2 
				ON T1.TEAM_ID = T2.TEAM_ID
		INNER JOIN PLAYER_POSITION AS T3 
				ON T1.PLAYER_POSITION_ID = T3.PLAYER_POSITION_ID
	WHERE TEAM_NAME = teamName;
END $$
DELIMITER ;

-- CALL GetByTeamName('Brazil');